### ISSUE TITLE
ply vertex colors not works

### ISSUE THREAD

**Issue by YanQiSun** [mitsuba-renderer/mitsuba3#1079]
I used Open3D to generate a Triangle Mesh and included RGB color information in its PLY file. However, after loading the PLY file in Mitsuba, I cannot see the colors. Here is the header information of the PLY file:

vbnet
Copy code
ply
format ascii 1.0
comment Created by Open3D
element vertex 53
property double x
property double y
property double z
property double nx
property double ny
property double nz
property double red
property double green
property double blue
element face 102
property list uchar uint vertex_indices
end_header
I couldn't find instructions in the Mitsuba documentation on how to correctly load color information from a PLY file. How can I make Mitsuba correctly load and display the color information from the PLY file? Or what should I do in the XML to ensure that the vertex colors are represented?

xml
shape type="ply" id="elm__6" name="elm__6"
    string name="filename" value="/home/sun/pro/colored_triangle_mesh_with_normals_ascii.ply"/
    boolean name="face_normals" value="true"/
    ref id="default-bsdf" name="bsdf"/
/shape

**Comment by njroussel** [comment]
Hi @YanQiSun 

You should take a look at the [`mesh_attribute` plugin](https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_textures.html#mesh-attribute-texture-mesh-attribute).

The `ply` shape is loaded with all your attributes (`red`, `green`, `blue`), however the BSDF is not aware of it. You can make the BSDF aware of them by using a `mesh_attribute` texture. 

You'll need to rename them with `someprefixofyourchoixe_{r, g, b}` as indicated in the [`ply` docs](https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_shapes.html#ply-stanford-triangle-format-mesh-loader-ply) if you wish to have a 3-channel texture rather than three 1-channel textures.
