### ISSUE TITLE
[❔ other question] Attaching a BSDF to a `Mesh` instance

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba3#109]
## Description

I'd like to create dynamically a mesh and pass it alongside the corresponding BSDF to `load_dict()`. If we would have some kind of `meshbuffer` plugin, it would work like this:
```python
my_mesh = mi.Mesh(...)

mi.load_dict({
    "type": "meshbuffer", 
    "mesh": my_mesh,
    "bsdf": {"type": "roughconductor"}
})
```
Basically, this would achieve functionality similar to that of `gridvolume`, to which a `VolumeGrid` instance can be passed directly (thanks a lot for adding this feature, by the way!).

Is such a workflow possible now? If not, I would greatly appreciate a bit of guidance on how to implement this functionality.

**Note:** I am aware that the following is possible:
```python
mi.load_dict({
    "type": "scene",
    "batmobile": my_mesh,
})
```
but I can't figure out how to set the BSDF.

**Comment by fschiffers** [comment]
I know this is closed/resolved, but maybe we can reopen this, such that it'll be added to some sort of documentation eventually?

It was really hard to find how to do this.

**Comment by cfreude** [comment]
Is there any news or updates on this?

I would like to add a `Sensor` to a procedurally generated and instanced `Mesh` directly via `Properties`, without writing the mesh first to a PLY, because this becomes slow with thousands of meshes.

If I try it via `Properties` I get: "RuntimeError: ​[distr_1d.h:236] DiscreteDistribution: no probability mass found!"
Is this because the `Sensor` is instanciated before the mesh is processed?

How could this be done, maybe via a custom plugin?

**Comment by Speierers** [comment]
@cfreude indeed this won't work in the current codebase. For now you might need to find a workaround using a custom `Mesh` plugin in `Python`.

**Comment by h-OUS-e** [comment]
Could we also add emitters to the mesh using properties? I am getting " "RuntimeError: ​[distr_1d.h:236] DiscreteDistribution: no probability mass found!" when trying to add one as well.
