### ISSUE TITLE
vscode intellisense (code autocomplete)

### ISSUE THREAD

**Issue by toaster-robotics** [mitsuba-renderer/mitsuba3#1179]
## Summary
Many functions/properties are not available for autocomplete on vscode.

## System configuration
vscode/pylance

## Description
Many functions/properties are not available for autocomplete on vscode. For example, the function **mitsuba.util.write_bitmap** does not autocomplete and has no type hints. This is the same problem that **pybullet** has ([issue link](https://github.com/microsoft/pylance-release/issues/663)). They resolved it by generating a stub file and having that in their working directory. I attempted to generate a stub file using mypy ([stub-gen](https://mypy.readthedocs.io/en/stable/stubgen.html)) however it fails because the mitsuba variant has to be declared. I'm guess the retargetable aspect of mitsuba is the reason why some of the autocomplete doesn't work. It would be great to have this ability for the entire library. It helps a lot with coding. Otherwise there's a lot of looking up old code or searching the documents. 

Below shows **write_bitmap** in white text, unlike **render** which is in yellow. This indicates an unknown function.
![Screenshot from 2024-05-21 22-40-24](https://github.com/mitsuba-renderer/mitsuba3/assets/141705577/d0b0ba27-8da1-49c2-a6d5-ba9a0c3b0182)
![Screenshot from 2024-05-21 22-49-26](https://github.com/mitsuba-renderer/mitsuba3/assets/141705577/4ccd6424-bd43-4cbb-a3b3-d3bbcf1824ab)

## Steps to reproduce
type out **mitsuba.util.write_bitmap** and try and get a type hint

**Comment by toaster-robotics** [comment]
I did some further digging and it seems there already is a stub file containing **write_bitmap**. It's under **stubs/scalar_rgb_util.pyi**. So maybe vscode doesn't know to look there when I retarget mitsuba to **scalar_rgb**?

**Comment by merlinND** [comment]
Hello @toaster-robotics,

I believe that the generated stubs will be much more complete in the next major version, with the transition to nanobind.

**Comment by njroussel** [comment]
From my experience, at the first formatting/syntax issue in any stub `.pyi` file the IDE's auto-completion system (ex: `pyright`) will halt. Well let's just fix the stub?! The issue is that we hand crafted a script to build these stub files because of the thousands of types and classes that Mitsuba contains. We've ran into many, many, many cases were we would produce some illegal syntax, I'm not surprised that some still exist. In short, although every symbol is declared in the stubs files, some are not picked up because of some error earlier in the parsing. 

We are transitioning to `nanobinds`'s [stub generation tool](https://nanobind.readthedocs.io/en/latest/api_cmake.html#stub-generation) which will be much more robust.
