### ISSUE TITLE
Won't compile without at least one _ad variant

### ISSUE THREAD

**Issue by Panjaksli** [mitsuba-renderer/mitsuba3#1311]
## Summary

The project won't compile (cryptic compile and linking errors) without specifying at least one _ad_ variant in mitsuba.config.

It wouldn't be a problem by itself, but  NOWHERE	in the docs, it is ever mentioned, that one _ad_ variant is mandatory.
Not in "read the docs" online,  and neither in the actual config itself... 
You only specify, that only mandatory variant is "scalar_rgb" and with regards to _ad_ variants, those are only "recommended".
Please make the instructions more explicit, because I've just wasted 20 hours of my life trying to make normal PT work on multiple platforms and compilers, just because I didn't need any differentiation when compiling.

**Comment by njroussel** [comment]
Hi @Panjaksli 

I've tried this myself, the lastest release does compile when only specifying `scalar_rgb`. Can you tell me more about your environement? Were you using `master` ? As mentionned in the README, `master` is undergoing a lot of undocumented changed - it's unstable. 
That being said, I'll change the documentation such that it gives cloning instruction for the latest release rather than `master`.

On `master` you indeed currently need to compile at least one AD variant, we'll either fix this or make it a requirement for the next release.

**Comment by rtabbara** [comment]
Hi @Panjaksli ,

> It wouldn't be a problem by itself, but NOWHERE in the docs, it is ever mentioned, that one ad variant is mandatory.

Sorry about that. I've now updated the developer guide [documentation](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html) to reflect this new requirement.

As a small silver lining, compilation times of Mitsuba 3 in general have gone down quite a bit since v3.6.0 (at least from my local benchmarks), so hopefully this isn't a huge inconvenience.
