### ISSUE TITLE
 I have no idea about "jit_flush_malloc_cache()" error  when use cuda_ad_rgb variants

### ISSUE THREAD

**Issue by ljijjiang1234** [mitsuba-renderer/mitsuba3#149]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 jit_flush_malloc_cache(): Dr.Jit exhausted the available memory and had to flush its allocation cache to free up additional memory. This is an expensive operation and will have a negative effect on performance. You may want to change your computation so that it uses less memory. This warning will only be displayed once.]

## Summary

*Sir,When I use cuda_ad_rgb to differentiate the paramater texture.data , There's something wrong called the "jit_flush_malloc_cache()" error , so I change the size of the texture.data to decrease the computation of my code,but the error still here ，So would you like to give me some advise to solve it?Maybe like how to extend the avaiable memory for cuda*

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform:Windows11 ...
- Compiler: ...
- Python version:3.9 ...
- Mitsuba 3 version: ...
- Compiled variants:
    * `cuda_ad_rgb`

**Comment by merlinND** [comment]
Hello @ljijjiang1234,

Could you please give us the following information:

- GPU model and available GPU memory
- What integrator are you using to render your scene?
- What are you trying to achieve: rendering an image, or computing gradients w.r.t. the scene parameters?
- At what resolution and spp are you trying to render?

In principle, if you are trying to run differentiable rendering, memory usage can be drastically reduced by switching to the `prb` integrator instead of `path`.

**Comment by ljijjiang1234** [comment]
Hello 
Thanks for your advice ,I just change the monte kalo samples for path algirithm , And I have solve the problem.
Anyway Thanks for your excellent job for rendering , By using this way  can implement so many Interesting tasks in graphics and vision.

**Comment by merlinND** [comment]
Glad it worked out! Looking forward to what you'll make with it :)
