### ISSUE TITLE
[✨ feature request] Progress bar like Mitsuba 2

### ISSUE THREAD

**Issue by UNakade** [mitsuba-renderer/mitsuba3#164]
## Summary

It would be helpful to show a progress bar while a scene is rendering.

## Description

It can take a long time for a scene to render. Having a progress bar like Mitsuba 2 would be very helpful. Is there already a way for us to enable this? If so, how? (I think it should be enabled by default)

**Comment by merlinND** [comment]
Hello @UNakade,

If you use `scalar_*` variants, you should see the same progress bar as before.
In JIT-compiled modes, at least in CUDA variants, the progress bar does not appear because control is completely handed off to the device. 
We have not implemented a mechanism for the device to provide updates to the host on rendering progress.
But even if there was one, I believe we would keep it off by default because such renderings are typically run in the inner loop of a differentiable rendering optimization — the progress bar then is over the iteration count.
