### ISSUE TITLE
Retrieve diffuse and specular reflectance values

### ISSUE THREAD

**Issue by LiuTaowen-Tony** [mitsuba-renderer/mitsuba3#170]
[❔ other question]

I would like to obtain the reflectance value for each ray at every bounce. I have generated a million rays from the camera. Currently, I can access each BSDF id using a for loop to iterate through:

bsdf = si.bsdf()                          # this bsdf is a BSDFPtr object, where each BSDF object inside is accessed using bsdf.entry_(idx)
for idx in range(num_of_rays):
        bsdf.entry_(idx).id()           # this returns the id of the BSDF object, which is a string

I then look up in the scene xml file to retrieve the corresponding reflectance to the BSDF id.

However, this is too slow for training. Do you either have a way to read ids of all BSDF of all the rays at the same time? Or if there is a more convenient way to read reflectance values for each ray? 

Furthermore, is there a functionality in DrJit that is similar to PyTorch's '.cpu()'?

**Comment by Speierers** [comment]
Hi,

Mitsuba 3 operates in wavefront, and for better performance I would highly recommand that you try keeping your workload in wavefronts as well. This means that the code you write should be "written for a single ray" and thanks to Dr.Jit this will be applied to all your rays at once seamlessly.

Take a look at other integrators implemented in Mitsuba 3 (e.g. `direct.cpp` or `prb.py`) to see how this is done in practice.  

In your case, what do you mean by "reflectance value"? Is this the albedo of the BSDF? Currently the BSDF interface doesn't provide a virtual function to query this, but this will likely be added in the upcoming release as we are working on supporting the Optix denoiser.

In anycase, a workaround for now would be to query the retro-reflection value at all BSDF like this (untested):
```python
si_retro = si
si_retro.wi = si.n
value = si.bsdf().eval(ctx, si_retro, si.n, active)
```

Otherwise you can also take a look at [this PR](https://github.com/mitsuba-renderer/mitsuba3/pull/22) to see how to add such functionality to the BSDF interface.

**Comment by LiuTaowen-Tony** [comment]
Thank you for your reply!

>> This means that the code you write should be "written for a single ray" and thanks to Dr.Jit this will be applied to all your rays at once seamlessly.

Yes, I would like to obtain the albedo of the BSDF at each bounce. Is there a way to obtain the BSDF ID using the .id() function for all rays at a single bounce simultaneously?

I think the bottleneck in my code now is that to obtain the id of each BSDF, I have to query each ray in the bsdf = si.bsdf() using the .entry_(i) but I can't get an array of the IDs using a single function.

For instance, I can get an array of the bsdf using si.bsdf() but I can't call bsdf.id() to get an array of the IDs.

Thank you!

**Comment by Speierers** [comment]
> Yes, I would like to obtain the albedo of the BSDF at each bounce. Is there a way to obtain the BSDF ID using the .id() function for all rays at a single bounce simultaneously?

You should be able to cast the bsdf pointers variable into a `UInt32` like this:
```
dr.reinterpret_array(mi.UInt32, si.bsdf())
```
This will give you an array of indices for the BSDFs.

**Comment by LiuTaowen-Tony** [comment]
I think in the documentation .id() will return a string identifier of the BSDF. How can I get this array of string identifiers using this array of indices? 

Thank you very much for your help!

**Comment by Speierers** [comment]
That is not going to work unless you make `id()` a virtual function. But Dr.JIT doesn't support arrays of strings so that won't work unfortunately. You will need to work with indices and only at the end convert those to the proper strings I suppose.

I will close this as it is not an issue.
