### ISSUE TITLE
Volumetric caustic sample scene renders with no caustics.

### ISSUE THREAD

**Issue by inversetrs** [mitsuba-renderer/mitsuba3#181]
- [🐛 bug report]
- [❔ other question]

## Summary

Volumetric caustic sample scene renders with no caustics. 

## Description
render:
![my_first_render](https://user-images.githubusercontent.com/98914046/185236104-7769dce6-2f06-4099-b2ef-7f92300807ac.png)
instead of expected:
![TungstenRender](https://user-images.githubusercontent.com/98914046/185236428-21b67e9b-f8bb-483b-9ca4-dd6e43cb0cd3.png)

## Steps to reproduce

Load sample scene from https://benedikt-bitterli.me/resources/mitsuba/volumetric-caustic.zip and render.

**Comment by Speierers** [comment]
I believe this is due to the complexity of the light transport occuring in this scene. The original image was likely rendered using photon mapping or bidirectional path tracing. Currently, those rendering algorithms aren't implemented in Mitsuba 3.

You can try to make the sphere rougher or the area light larger to recover some sort of caustic, but it won't look the same unfortunately.

**Comment by inversetrs** [comment]
Thanks! Would the photonmapper integrators/ plugins at the original mitsuba suffice for this? In the sample scenes .zip there is a v0.6 version of the scene that uses the sppm integrator. 
If I was to try, would it be straightforward to port the plugin from mitsuba to mitsuba3, or there are some catches?   thanks again for the great work!

**Comment by Speierers** [comment]
Yes that integrator should work also I don't think it will be straightforward to port is to Mitsuba 3. If you want to give this a shot, please open a PR and I will be more than happy to help you with this.
