### ISSUE TITLE
warning: drjit location is where expected, but still warns

### ISSUE THREAD

**Issue by jeertmans** [mitsuba-renderer/mitsuba3#302]
## Summary

When importing Mitsuba package, I get a warning saying that `drjit` was not installed at the expected location, while it actually is.

## System configuration

System information:

  OS: Ubuntu 22.04 LTS
  CPU: Intel(R) Xeon(R) W-1370P @ 3.60GHz
  GPU: NVIDIA GeForce RTX 3070
  Python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  NVidia driver: 510.85.02
  CUDA: 11.6.112
  LLVM: 13.0.1

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

One image says it all:

![image](https://user-images.githubusercontent.com/27275099/193797830-0fccda6a-3661-4cb0-9f28-bab21a8404c4.png)

## Steps to reproduce

1. Just did a fresh installation with `pip install mitsuba`

**Comment by njroussel** [comment]
This is rather surprising.
The warning is there to check that `drjit` in a specific path **relative** to `mitsuba`. Do you mind running this snippet to tell me where you `mitsuba` installation is?
```
import mitsuba as mi
print(mi.__path__)
```

This might just be a spurious warning because Python's `os.path.relpath` is behaving bizarrely in your setup/environment. So you might still be able to run `mitsuba` without any issues.

**Comment by jeertmans** [comment]
There you have @njroussel:
```python
>>> import mitsuba
>>> print(mi.__path__)
['/home/eertmans/.local/lib/python3.10/site-packages/mitsuba',
 '/home/eertmans/.local/lib/python3.10/site-packages/mitsuba/python']
```

Well, yes, it really seems like a spurious warning since everything seems to work fine.
