### ISSUE TITLE
Rendering after modifying mesh vertex positions appears to use face normals and ignore interpolated vertex normals

### ISSUE THREAD

**Issue by Sam-Izdat** [mitsuba-renderer/mitsuba3#320]
## Summary

OBJ mesh's smooth, interpolated vertex normals seem to disappear when vertex positions are updated in an existing scene.

## System configuration

System information:

  OS: Linux (Ubuntu 22.04 LTS)
  CPU: Intel Xeon E5-2699 v3
  GPU: NVIDIA Tesla K80
  Python version: 3.9.12
  LLVM version: 14.0.0
  CUDA version: 11.4
  NVidia driver: 470.141.03
  Dr.Jit version: 0.2.2
  Mitsuba version: 3.0.2
     Compiled with: GNU 10.2.1
     Variants compiled:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Creating a scene, accessing a mesh's vertex positions with `dr.unravel(mi.Point3f, params['mesh.vertex_positions'])`, applying any transform to them (e.g. `vpos.z += 0.1` or `vpos_new = mi.Transform4f.rotate(axis=[0, 0, 1], angle=20) @ vpos_old)`, raveling, updating scene params and re-rendering appears to discard smooth interpolated vertex normals and use face normals instead.

Tried setting `face_normals` to `false` explicitly to no avail. 

Original position:
![vertex_normals](https://user-images.githubusercontent.com/2222161/195071385-ecb08a9d-617a-415c-b26a-260061301a9e.png)

Translation:
![face_normals](https://user-images.githubusercontent.com/2222161/195071301-37f2b59d-5a71-45fa-986d-42d9112ccbeb.png)

## Steps to reproduce

1. Load a scene from XML file which uses an OBJ mesh with vertex normals
2. Render the scene
3. Unravel the mesh's `vertex_positions`
4. Apply any transform 
5. Ravel and assign new vertex positions
6. Update scene params
7. Re-render the scene

**Comment by Sam-Izdat** [comment]
Sure.  Attaching archive.  I hope it's easy enough to see the faceting in the specular highlights on this mesh.

[face_normals_repr.tar.gz](https://github.com/mitsuba-renderer/mitsuba3/files/9756551/face_normals_repr.tar.gz)

Python script:

```python
import drjit as dr
import mitsuba as mi

mi_xml = "" # OMITTED

mi.set_variant('llvm_ad_rgb')
scene = mi.load_string(mi_xml)
cam = mi.load_dict({
    'type'          : 'perspective',
    'fov_axis'      : 'smaller',
    'focus_distance': 6.0,
    'fov'           : 28.8415,
    'to_world'      : mi.ScalarTransform4f.look_at(
        target=[3.04072, -2.85176, 2.80939],
        origin=[3.69558, -3.46243, 3.25463],
        up=[-0.317366, 0.312466, 0.895346]
    ),
    'sampler' : {
        "type" : "ldsampler",
        "sample_count" : 64
    },
    'film': {
        'type': 'hdrfilm',
        'width': 512,
        'height': 512
    }
})

params = mi.traverse(scene)

sb_vp = dr.unravel(mi.Point3f, params['shaderball.vertex_positions'])
sb_vp.z += 0.1
params['shaderball.vertex_positions'] = dr.ravel(sb_vp)
params.update()
img = mi.render(scene, sensor=cam, spp=256)
mi.util.write_bitmap('result.png', img, write_async=False)
```

**Comment by njroussel** [comment]
Hi @Sam-Izdat 

It took me some time to figure out what was going on here :sweat_smile: .

After updating the `vertex_positions` parameter, if the mesh has normals, it will **always** recompute them as face normals.
In your use case, it's unfortunate since you're simply applying a translation. However for more complex transformations, the assumption is that we cannot keep the existing vertex normals and hence must recompute them (use face normals).

For now, you can manually copy and replace the normals to keep their values. Like so: 
```
params = mi.traverse(scene)
normals = mi.Float(params['shaderball.vertex_normals']) # Copy normals

params['shaderball.vertex_positions'] = new_vertex_positions
params.update() # Vertex normals are recomputed
params['shaderball.vertex_positions'] = normals  # Replace normals with their original value
params.update()
```
You will have to make the normals replacement in a second and separate update. If it's done in the same update, face normals will be computed and applied.

This isn't very user-friendly and we might want to change this. I'll keep this issue open for now.

**Comment by njroussel** [comment]
Hi [@Sam-Izdat](https://github.com/Sam-Izdat)

It took me some time to figure out what was going on here :sweat_smile:

After updating the `vertex_positions` parameter, if the mesh has normals, it will always recompute them. The exact algorithm might not preserve the appearance you originally had, it's a best effort solution to preserve smoothness. Here's the exact code: https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/render/mesh.cpp#L257-L346.

In your use case, it's unfortunate since you're simply applying a translation. However for more complex transformations, the assumption is that we cannot keep the existing vertex normals and hence must recompute them.

For now, you can manually copy and replace the normals to keep their values. Like so:
```
params = mi.traverse(scene)
normals = mi.Float(params['shaderball.vertex_normals']) # Copy normals

params['shaderball.vertex_positions'] = new_vertex_positions
params.update() # Vertex normals are recomputed
params['shaderball.vertex_positions'] = normals  # Replace normals with their original value
params.update()
```
You will have to make the normals replacement in a second and separate update. If it's done in the same update, new normals will be computed and applied.

Inherently, this is something that begins with the mesh. If you take a look at the shaderball, you'll set that it's mostly split quads, hence the faceted appearance. In general, it might be easier to modify the mesh directly such that it's vertex normals are closer to the re-computation scheme in mitsuba.
