### ISSUE TITLE
How to specify a GPU card?

### ISSUE THREAD

**Issue by Daiqy** [mitsuba-renderer/mitsuba3#328]
## Summary

How to specify a GPU card?

## System configuration

System information:

  OS: Ubuntu 20.04
  GPU: Nvidia 3090

  Mitsuba version: 3.0.2
     Variants compiled: cuda_ad_rgb

## Description
Hi, 
I am running mitsuba3 on a machine with multiple GPUs. I am wondering what the ways are to specify a GPU card mitsuba3 will run on?
In addition, if I use PyTorch and Mitsuba in one code, can I specify separate GPUs for them? I want to make the PyTorch neural network model and Mitsuba run on different GPU cards.
Thank you!

**Comment by Speierers** [comment]
Hi @Daiqy, you can use `CUDA_VISIBLE_DEVICES="..."` to specify which GPU to be used when launching a Python script.

Otherwise, you should be able to use `dr.set_device(...)` to specify which GPUs to be used by Dr.Jit. You can also take a look at this forum [thread](https://discuss.pytorch.org/t/running-on-specific-gpu-device/89841/8) to see how to achieve this in PyTorch as well.
