### ISSUE TITLE
How can I define a light source ?

### ISSUE THREAD

**Issue by oferyaron** [mitsuba-renderer/mitsuba3#329]
Hi, 
How can I define a light source ?
I would like to define a stage light .
It characterized by the angular beam width,
the projector's aperature and the total intensity in watts.

**Comment by Speierers** [comment]
Light sources need to be defined in the XML scene file: [documentation](https://mitsuba.readthedocs.io/en/stable/src/key_topics/scene_format.html)

Mitsuba implements a few [emitter plugins](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_emitters.html) that should cover your needs. Otherwise you might want to implement you own emitter plugin in C++ or Python.
