### ISSUE TITLE
why mi.Bitmap() rotates the image ,which is of numpy.ndarray type?

### ISSUE THREAD

**Issue by anewusername77** [mitsuba-renderer/mitsuba3#456]
## Summary

when using `b_img = mi.Bitmap(img)`, img is of type `numpy.ndarray`, and saving it with `b_img.write('file.png')`, this img is rotated 90 degrees comparing to save it with`plt.imwrite('filename.png', img)`.

## System configuration

System information:

  OS: Ubuntu 20.04.4 LTS
  CPU: Intel(R) Xeon(R) Platinum 8276L CPU @ 2.20GHz
  GPU: Tesla V100-PCIE-32GB
Tesla V100-PCIE-32GB
  Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
  NVidia driver: 470.129.06
  LLVM: 12.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## reproduce steps
code as folllows:
```python
import matplotlib.pyplot as plt
import mitsuba as mi
mi.set_variant("llvm_ad_rgb")

img = plt.imread('filename.png')  # which is wrote by plt.imsave(), dtype=float32, size:(256,256,3)
b_img = mi.Bitmap(img)
b_img.write('filename2.exr')
```
one weird thing is, after changing code to:
```python
img = plt.imread('filename.png') 
img = cv2.rotate(img, cv2.ROTATE_180)
img = cv2.rotate(img, cv2.ROTATE_180)
b_img = mi.Bitmap(img)
b_img.write('filename2.exr')
```
the result becomes correct.

**Comment by njroussel** [comment]
Hi @anewusername77 

I have not been able to reproduce this issue.

Can you try using a non-square image to try to identify where your issue is happening?
For example, if you `print(b_img)` you should be able to see the resolution of the image. It would be good to identify if it's during the construction `b_img = mi.Bitmap(img)` or during the final `b_img.write()` that this issue is happening.

The extra rotatations in your second snippet really should have no influence. Mitsuba is totally unaware of them. You can maybe add an assert to double check that nothing has changed in your image after the rotations to validate this too.

**Comment by anewusername77** [comment]
thanks,  I'll try. 
btw, is it possible to optimize `specular` and `base_color` in `principled bsdf` during backpropagation in pytorch? after changing bitmap to tendsorXf for `base_color`, the `needs_differential()` function still returns `False`.

**Comment by njroussel** [comment]
Yes that should be possible. The `needs_differential()` method is something unrelated to what you are trying to do. It has to do with fields that need to be computed during the ray-shape intersection for some BSDFs.

Please, open new discussions/issues for such questions. It helps other users find them :)

**Comment by anewusername77** [comment]
thanks, I'll start a new issue
