### ISSUE TITLE
Depth integrator example gives 10mm error in depth map

### ISSUE THREAD

**Issue by cartacamilla** [mitsuba-renderer/mitsuba3#491]
## Summary

The distance of a rectangle from the camera is off of 1cm compared to what it should be. 

## System configuration

System information:

  OS: Ubuntu 22.04.1 LTS
  CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  GPU: NVIDIA GeForce RTX 2060 SUPER
  Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  NVidia driver: 525.60.13
  CUDA: 11.2.152
  LLVM: 13.0.1

  Dr.Jit: 0.3.0
  Mitsuba: 3.1.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_mono
        llvm_ad_mono
        cuda_ad_mono

## Description

I'm reproducing a simple example I found in the doc of Mitsuba 2 ([depth integrator](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/02_depth_integrator/depth_integrator.py)).
The script is working great after setting the right variant, but the depth I plot is 10mm wrong. For example, with a basic rectangle at 1m from the camera, the minimum depth point is 0.99m. I tested other distances and the error is still 10mm.

I get the same result for the "cuda" variant.

## Steps to reproduce

1. Create simple scene with rectangle at 1m:
```xml
<scene version="2.2.1">
  <integrator type="path">
    <integer name="max_depth" value="3"/>
  </integrator>

  <sensor type="perspective">
    <transform name="to_world">
      <lookat origin="0, 0, 1" target="0, 0, 0"/>
    </transform>
    <film type="hdrfilm">
      <rfilter type="box"/>
      <string name="pixel_format" value="luminance"/>
      <integer name="height" value="320"/>
      <integer name="width" value="270"/>
    </film>
  </sensor>

  <shape type="rectangle" id="wall">
    <bsdf type="roughdielectric"/>
	<transform name="to_world">
      <scale value="1"/>
      <translate x="0" y="0" z="0"/>
    </transform>

  </shape>
</scene>

```
2. Run test script:
```python
import drjit as dr
from mitsuba import load_file, Point2f

filename = "wall.xml"

scene = load_file(filename)

sensor = scene.sensors()[0]
film = sensor.film()
sampler = sensor.sampler()
film_size = film.crop_size()
spp = 1

# Seed the sampler
total_sample_count = int(np.prod(film_size) * spp)

if sampler.wavefront_size() != total_sample_count:
    sampler.seed(0, total_sample_count)

# Enumerate discrete sample & pixel indices, and uniformly sample
# positions within each pixel.
count = np.arange(total_sample_count) // spp

scale = (1.0 / film_size[0], 1.0 / film_size[1])
pos = Point2f(np.vstack([count % film_size[0], count // film_size[0]]).T) + sampler.next_2d()

# Sample rays starting from the camera sensor
rays, weights = sensor.sample_ray_differential(time=0, sample1=0, sample2=pos * scale, sample3=0)

# Intersect rays with the scene geometry
surface_interaction = scene.ray_intersect(rays)

# Given intersection, compute the final pixel values as the depth t
# of the sampled surface interaction
result = surface_interaction.t

# Set to high number if no intersection was found
result[~surface_interaction.is_valid()] = 10

res = result.numpy().reshape((film_size[1], film_size[0]))
min_point = np.unravel_index(res.argmin(), res.shape)

print(f"Minimum value: {res.min()}, {min_point}")

import matplotlib.pyplot as plt

plt.imshow(res)
plt.plot(min_point[1], min_point[0], "or")
plt.text(
    min_point[1],
    min_point[0] + 20,
    f"Min: {res.min()}",
    horizontalalignment="center",
    color="red",
)
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/32430116/212345024-582d7a8a-5c39-4389-8ac4-d9b404988b34.png)

**Comment by njroussel** [comment]
Hi @cartacamilla 

I believe this is because the ray's origin is actually set on the "near" plane of the perspective projection.
You can see the default values in the [plugin documentation](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_sensors.html#perspective-pinhole-camera-perspective).

Changes to this `near_clip` parameter, should be reflected in your plot.

**Comment by cartacamilla** [comment]
Thank you @njroussel for your answer.

After applying a different `near_clip` value, I obtained indeed the right value of depth.

This means that the ray cannot start at position 0 as  the sensor's `near_clip` value cannot be set to 0.  
What is the reasoning behind this decision? It seems that this has changed since Mitsuba 2. As I understand it, now the ray's length is clipped between [near, far] plane instead than [0, far]. Am I assuming correctly? 

Could you also let me know if this approach to compute the depth inspired by the [depth integrator](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/02_depth_integrator/depth_integrator.py) example for Mitsuba 2 is still correct, or if there is a better way to compute the depth map?

**Comment by njroussel** [comment]
I'm not familiar enough with Mitsuba 2 to say exactly what has changed, but it seems like the `near_clip` limit already existed in Mitsuba 2: [source code](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/librender/sensor.cpp#L101) :man_shrugging: 

If the `near_clip` distance defines the plane in which the sensor's film is supposed to be placed, then for `near_clip == 0`  a single point is not only the origin of all rays but also your entire film. Every pixel would have zero width/height, right?
I think that's why the near_clip cannot be zero.

 Your approach definitely isn't wrong, but there are indeed a few other ways in which you could achieve the same result:
 * Use the [depth integrator](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_integrators.html#depth-integrator-depth) 
 * Use the [AOV integrator](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_integrators.html#arbitrary-output-variables-integrator-aov) and [extract the depth](https://mitsuba.readthedocs.io/en/stable/src/how_to_guides/image_io_and_manipulation.html#Multichannel-images)
 * Write a custom renderer script, as you are doing but making more use of `drjit` rather than `numpy`. [Here](https://mitsuba.readthedocs.io/en/stable/src/rendering/scripting_renderer.html)'s a good example.
