### ISSUE TITLE
Why are many parameters non-differentiables/not shown by `mi.traverse`?

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mitsuba-renderer/mitsuba3#531]
Hello,

I was experimenting a little bit with Mitsuba 3 and doing `mi.traverse` on a scene I was surprised to observe:

- When wrapping shapes into shape groups, we lose access to all the parameters of the children (they are not displayed by the traverse function)
- It seems possible to differentiate the vertices of a given shape but not the `to_world` matrix of shapes nor cameras. Is there something to enable to get those. It seems that getting the gradient wrt the `to_world` matrix should be doable assuming one have the gradient on each individual vertices no ?

Thank you for the clarifications!

**Comment by njroussel** [comment]
Hi @GuillaumeLeclerc 

Unfortunately your issue was lost in another repository :frowning_face: 

I think most of the questions you had were implemented in [v3.1.0](https://github.com/mitsuba-renderer/mitsuba3/releases/tag/v3.1.0) :tada:. :
* `shapegroup` children parameters are exposed
* `Sensor` paramaters are exposed and differentiable
* Primitive shapes like `disk`, `sphere`, `rectangle` are differentiable

For shapes, the `to_world` matrix is baked into the vertex positions. However, it is still possible to track and apply gradients to a transform applied to all vertices (like `to_world`). Take a look at this tutorial: https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/object_pose_estimation.html

**Comment by GuillaumeLeclerc** [comment]
Thank you very mych I will take a look at this!
