### ISSUE TITLE
NEE issue on medium boundary with volpath and volpathmis

### ISSUE THREAD

**Issue by dargouder** [mitsuba-renderer/mitsuba3#538]
## Summary

Next-event estimation on a medium boundary surface in both **volpath** and **volpathmis** is not working as expected due to a possible issue with the parameters passed to `sample_emitter`, which leads to a random walk starting again when the ray has supposedly already exited the medium. This results in a darker image.

## System configuration

  OS: Windows-10
  CPU: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
  GPU: NVIDIA GeForce RTX 3090 Ti
  Python: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
  NVidia driver: 526.47
  CUDA: 11.8.89
  LLVM: 0.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: MSVC 19.33.31630.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        cuda_ad_spectral

## Description

Next-event estimation on a medium boundary surface in both **volpath** and **volpathmis** call a function called `sample_emitter`. This function is being passed the medium inside the boundary, even when called on the surface of the boundary, after exiting the medium. As a result, flags such as `active_medium` end up in a different state from those in the caller ( the `sample` function ).
This leads to a random walk starting again when the ray has supposedly already exited the medium.

This is particularly problematic if a Dirac emission profile is used.

One tentative fix would be to pass a nullptr when calling sample_emitters during surface NEE. This would be done here:
https://github.com/mitsuba-renderer/mitsuba3/blob/0e497163e13a27d7afe5beb591f6fd7bac7ce80d/src/integrators/volpath.cpp#L281

I have confirmed this to be an issue by rendering the same scene using mitsuba 0.6 and comparing images from mitsuba 3 with both the fix and the original source code.

The tentative fix image is similar to the mitsuba 0.6 image, whilst the original source code produces a different result.

I have included exrs and test scenes for in the attached zip file.
[mitsuba_ticket.zip](https://github.com/mitsuba-renderer/mitsuba3/files/10664350/mitsuba_ticket.zip)
## Steps to reproduce

1. Extract zipfile
2. mitsuba box_m3.xml

**Comment by njroussel** [comment]
Hi @dargouder 

Thank you for the detailed bug report!

I believe there is indeed an issue in our volumetric integrators. The issue/solution is slightly different than what you describe though: we should actually set the medium depending on the sampled emitter direction. Currently any rays that escape the medium will always consider that they are still in it, but actually we should **still** consider that it's in the medium if the sampled ray direction points back into the medium.
Do you agree?

I'm currently writing a few tests to confirm my suspicion.

**Comment by dargouder** [comment]
I wondered about this too and I am only on the fence about it because:

If NEE is being performed on the exterior of the volume boundary, and the sampled ray direction points towards the interior (due to some backlighting for example), we would need an additional scattering event at the boundary re-entry point which should give back the medium. I would also expect NEE to fail in this case given the sampled direction cannot directly connect to the emitter.

I would be keen to hear about any tests that you are running as I am working a lot in this area, but we can take that discussion to another _medium_ (pun semi-intended).

**Comment by njroussel** [comment]
Sorry for the delay, I got side-tracked with other issues.
_____

> need an additional scattering event at the boundary 

I don't believe so. The BSDF scattering should suffice here, or is this what you meant?  We adjust for the BSDF's value here: https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/integrators/volpath.cpp#L283-L291

> I would also expect NEE to fail in this case given the sampled direction cannot directly connect to the emitter

This is true only if the enclosing BSDF [is not a `null`-like BSDF](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/integrators/volpath.cpp#L416-L418) (for the same reasons that we have the `sample_emitters` parameter in `homogeneous` or `heterogeneous` plugins). Of course, in your specific scene/setup it should fail because of the `roughdielectric`.
The extreme case to consider is when the shape is only partially "open", like when using the `mask` plugin.


Another important case to consider is if we're still within the medium's boundary shape but have hit another shape. Let's stay we have a cube with a `null` BSDF which also holds a homogeneous medium, and inside the cube there is a diffuse sphere. Then we can have a surface interaction on the sphere where emitter sampling is still possible. Moreover, during the emitter sampling, we must take into account the extinction between the sphere and the cube.
Similarly, there could also be an emitter within the medium.

Please take a look at https://github.com/mitsuba-renderer/mitsuba3/pull/552. I'm adding some of my test too, so that you can take a look.

**Comment by dargouder** [comment]
This makes a lot more sense and corrects a lot of wrong assumptions I had. Thank you for working on this so promptly!
