### ISSUE TITLE
PRB memory usage grows with number of SPP

### ISSUE THREAD

**Issue by Speierers** [mitsuba-renderer/mitsuba3#655]
While profiling inverse rendering optimization using the `prb` integrator, I realized that the memory usage of the integrator grows as I increase the number of samples per pixel (or the render resolution). My understanding was that such integrator works in a megakernel fashion, hence thread rendering state should stay in registers and only the output image / gradients would be stored in VRAM.

Looking at `common.py`, I noticed that we are scheduling the `state_out` variable in between the different phases of the PRB algorithm (see the following [line](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/python/python/ad/integrators/common.py#L937)). If not scheduled, I observe the expected behaviour (e.g. no scaling in memory usage).

Would it make sense to **not** schedule this variable, hence "fusing" the two phases in a single kernel launch but saving us from extensive memory usage? I suppose that this would also duplicate some of the computation, as a first kernel will be launched when developing the film (phase 1), and a second kernel will be launched for phase 2, re-computing the `state_out` values in this second kernel. Further reordering in this method will likely be necessary to completely fuse the two phases into a single `ray_gen` kernel. Any other option?

The same seems to be true for the `render_forward()` method, where the `state_out` variable is explicitly evaluated.

**Comment by njroussel** [comment]
Hi @Speierers  :smile: 

Let's write this out explicitly to avoid confusion (considering only the backward case):

During the `render_backward()` we currently have 3 kernels:
1) Does a primal rendering (first phase). This kernel's size is equal to the total number of samples.
2) Develops the film of the primal rendering (first phase). This kernel's size is equal to  `#pixels * #channels`.
3) Does the backward mode rendering (second phase). This kernel's size is equal to the total number of samples.

If you do not schedule `state_out` you'll still get 3 kernels with the difference that 3) practically re-computes 1). This is specifically true for `prb` as `state_out` matches `L`.
I guess my confusion comes from your use of "fusing". We will **always** have 3 kernels, right? The first two kernels will always be split apart because of their different sizes. The difference here is what kernel 3) computes and what input variables it will take.

I understand your initial point and agree that we should at least offer the option of this tradeoff: virtually rendering once more vs. using more VRAM memory.

**Comment by njroussel** [comment]
I just don't see how you could compute 3) (or 4) for that matter) without knowing 2). You need the differential radiance `δL` to compute 3) which I believe you can only get from 2). 
Either way, I don't want to slow you down. I'll be happy to review your patch if you figured this out.
