### ISSUE TITLE
High Memory Usage for Large Scenes

### ISSUE THREAD

**Issue by jparr721** [mitsuba-renderer/mitsuba3#710]
## Summary

I am experiencing extremely high RAM usage for scenes which require lots of geometry. Specifically, I have files totaling roughly between 2 and 8 gigabytes of disk space, the vast majority of which is using the "cylinder" primitive. We are rendering hair-like meshes and the cylinder is used to approximate the look of hair. The memory usage scales roughly to the following formula:

<file_size_gb> x 10 x 2.

So, an 8 gig file is roughly 8 * 10 * 2 = 160gb of RAM usage, per scene. I am not necessarily hunting for a "fix" here as much as I am seeking guidance as to why this is happening. I noticed that this memory behavior is persistent all the way back to Mitsuba 1. The example scene is as follows, but note that this occurs regardless of the sampling parameters, etc.

```xml
<scene version="3.0.0">

    <!-- Defaults, these can be set via the command line: -Darg=value -->

    <default name="spp" value="300"/>
    <default name="resx" value="1920"/>
    <default name="resy" value="1080"/>
    <default name="max_depth" value="8"/>

    <!-- Camera and Rendering Parameters -->

    <integrator type="path">
        <boolean name="hide_emitters" value="true"/>
        <integer name="max_depth" value="$max_depth"/>
    </integrator>
    <sensor type="perspective">
        <string name="fov_axis" value="y"/>
        <float name="fov" value="45"/>
        <transform name="to_world">
            <lookat origin="7.36662, 10.9175, 59.9311" target="7.24475, 10.7761, 58.9487"
                    up="0.0176622, 0.989334, -0.144589"/>
        </transform>
        <sampler type="multijitter">
            <integer name="sample_count" value="$spp"/>
        </sampler>
        <film type="hdrfilm">
            <string name="pixel_format" value="rgba"/>
            <rfilter type="gaussian"/>
            <integer name="width" value="$resx"/>
            <integer name="height" value="$resy"/>
        </film>
    </sensor>

    <!-- Materials -->
    <bsdf type="twosided">
        <bsdf type="roughplastic" id="brown">
            <float name="alpha" value="0.01"/>
            <string name="distribution" value="ggx"/>
            <float name="int_ior" value="1.55"/>
            <float name="ext_ior" value="1"/>
            <boolean name="nonlinear" value="false"/>
            <!-- BROWN HAIR -->
            <rgb name="diffuse_reflectance" value="0.143016, 0.0156076, 1.80928e-005"/>
        </bsdf>
    </bsdf>

    <!-- Emitters -->
    <emitter type="envmap" id="Area_002-light">
        <string name="filename" value="../envmap.exr"/>
        <float name="scale" value="3"/>
    </emitter>

    <!-- Fill Light -->
    <shape type="sphere">
        <point name="center" x="40" y="3" z="30"/>
        <float name="radius" value="10"/>
        <emitter type="area">
            <rgb name="radiance" value="6.0, 5.0, 6.0"/>
        </emitter>
    </shape>

    <!-- Shapes -->
    <shape type="sphere">
        <float name="radius" value="15.25"/>
        <transform name="to_world">
            <rotate x="1" angle="90"/>
        </transform>
        <bsdf type="twosided">
            <bsdf type="diffuse">
            </bsdf>
        </bsdf>
    </shape>

</scene>
```
Please note that this file is the _baseline_ file that I use. I edit the file using a python script to insert cylinders which look roughly like the following:
```
<shape type="cylinder"><float name="radius" value="0.0080000000000000002"/><point name="p0" x="-13.086031427683935" y="3.44499891596422" z="-17.449833548739988"/><point name="p1" x="-13.024401817120134" y="3.6631399999999998" z="-17.582703896490191"/><ref id="plastic-bsdf" name="bsdf"/>
```

## System configuration

System information:
The systems tested were a gamut of intel and apple machines, all of which exhibited high memory usage. The operating systems in use in particular were Ubuntu 20.04, CentOS 7, MacOS Ventura, but I must stress that the high memory usage occurs regardless of host, compiler flags, etc.

## Description

See above.

## Steps to reproduce

1. Create a script with the xml file provided above
2. Insert some amalgamation of cylinders until the file size is considerable (> 1 gig). I can provide a file if needed.
3. Observe high usage.

**Comment by njroussel** [comment]
Hi @jparr721 

I'm not quite sure how to answer this or what answer you're looking for. 

I've quickly inspected the sizes of the `Cylinder` hierarchy:
```
sizeof(Cylinder): 912
sizeof(Shape): 880
sizeof(Object): 16
```
Nothing seems to be particularly wrong with cylinders, rather all `Shape` objects have a significant overhead. I don't have time to track down all the memory usage for a `Shape`, but just from this we can see that the XML representation is about 250B and a cylinder is roughly 1kB. This is still not the 20x factor that you've observed, but there are a lot of different things that are still missing (scene holds a reference to shapes, the acceleration structure too, etc.).

In general, the memory consumption should still grow linearly with the number of shapes. Also, when dealing with a large amount of shapes that share the same properties (BSDFs for example), it is **always** preferable to use an "aggregate" object rather than thousands on individual smaller objects. For example, meshes are a single `Obj`/`Ply` object rather than thousands of `Triangle` objects because we can significantly reduce the overhead that they share. For cylinders specifically, this would need to be something you implement yourself, it does not exist in the current system.

I hope this helped :smile: 

I'll close this issue, unless you can point to something specific I don't think there's anything fundamentally wrong here.

**Comment by wjakob** [comment]
Also, worth noting that there are now fiber shapes composed of multiple segments in the latest version of the system (both linear and b-spline variants). If you can use those, it will dramatically improve performance.

**Comment by jparr721** [comment]
Ah yes, thank you @wjakob! We were looking for something like this. Also thank you @njroussel as well, I was mostly just looking for someone to confirm that it might lead to higher-than-expected usage, so this has answered both of my questions.

**Comment by jparr721** [comment]
Following up, the strands represented as fiber shapes had a night-and-day difference in performance and memory usage. Thank you for letting me know about this.
