### ISSUE TITLE
[🐛 bug report] Python Crashes when Trying to Render Scene without calling Update on Parameters

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba3#720]
## Summary

When calling `mi.render` on a scene without calling `params.update()`, the python instance crashes sometimes with an error message that is opaque (it's not immediately clear that one tried to render the scene without calling `params.update()`) or sometimes with no message at all depending on how the jupyter environment is run. 

## System configuration

```
  OS: Windows-10
  CPU: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 531.68
  CUDA: 11.7.99
  LLVM: 15.-1.-1

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? False
     Compiled with: MSVC 19.34.31937.0
```
<details>
  <summary>Variants:</summary>

```
        scalar_rgb
        scalar_mono
        scalar_mono_double
        scalar_mono_polarized
        scalar_mono_polarized_double
        scalar_rgb_double
        scalar_rgb_polarized
        scalar_rgb_polarized_double
        scalar_spectral
        scalar_spectral_double
        scalar_spectral_polarized
        scalar_spectral_polarized_double
        llvm_ad_rgb
        cuda_ad_rgb

```
</details>

## Description

Attempting to render a scene where `params.update` hasn't been called after updating scene parameters leads to the python instance crashing with errors like ```Critical Dr.Jit compiler failure: jit_var_gather(): operand r1516 remains dirty following evaluation!``` I would reasonably expect that this should throw an exception that can be caught and remediated by the programmer rather than forcing a re-run of all the code.

Especially problematic in a jupyter or ipython environment where sometimes the purpose is to explore various approaches to a problem and manually run cells in a non-linear order.

## Steps to reproduce

1. Open `tutorials/inverse_rendering/caustics_optimization.ipynb`
2. Comment out `params_scene.update()` in `apply_displacement` (Cell 14)
3. Run rest of notebook.

**Comment by njroussel** [comment]
Hi @Microno95 

Unfortunately this is not something we can reasonably change or improve.

The call to `params.update()` recursively propagates any changes to a child plugin to its parents. Without such a call the top-level plugin, let's say a `Scene`, might be in some inconsistent state which can lead to various bizarre errors messages. 

Implicitly calling `params.update()` on every parameter change is difficult to implement and could come at a significant performance cost. Imagine we're updating two meshes, after the first `params['mesh1.vertex_positions'] = new_positions` we update the acceleration structure, just for it to be overwritten during the second `params['mesh2.vertex_positions'] = new_positions2`.

**Comment by leroyvn** [comment]
Hi @njroussel, I'm not sure if you and @Microno95 understood each other: it seems to me that rather than an automatic call to `params.update()`, he is asking if it would be possible to raise an exception, upon call to `mi.render()` after an incomplete parameter update, rather than let Python crash. This has indeed the unpleasant side effect of killing iPython kernels, forcing the user to re-run a WIP notebook.

**Comment by Microno95** [comment]
Yep, that's exactly what I was suggesting. Some method of recovery from not correctly calling `update()` rather than completely killing off the python instance.

Perhaps as an internal flag that can be checked similar to how `SceneParameters` tracks which nodes are marked dirty and updates on them on the next call to `update()`.

**Comment by njroussel** [comment]
Sorry for the delay, I'm still catching up with these discussions/issues whenever I have time.
I wasn't explicit enough in the first few sentences of my original response.

Without a call to params.update(), some parts of the scene will be in an inconsistent state. For example, consider some pointer that hasn't been updated correctly. In such a case, most operations involving this pointer will segfault which cannot be recovered and cannot keep the Python process alive (reasonably). Even in cases where we check the operands and can therefore throw an error message, such as the one in your original issue message, it is difficult if not impossible to disambiguate if the cause of the problem is a user error or a fault in Dr.Jit itself. We assume the latter, which means that something went terribly wrong in the just-in-time compiler and we can no longer trust it, prompting a SIGABRT signal. I think it's clear that this whole issues should be handled higher up in Mitsuba, rather than deep in Dr.Jit.

As [@Microno95](https://t.me/Microno95) suggested, we would ideally need each plugin to be aware of it's own state. This means that a plugin should know when one of its attributes has changed and when it needs to re-compute its internal state. I think it's clear that we offloaded this responsibility and complexity to the `SceneParameters` class.

I completely agree that's it's an unfortunate problem. There is a clear proportionality gap between the simple one-line fix of adding `params.update()` and the consequences of operations on a dirty plugin/scene: error, crash, restart, etc. If you have any reasonable and tangible solutions, I'm happy to discuss them. Every solution that comes to my mind would either need an overhaul of the `traverse` mechanism, have a performance cost, or add extra complexity to each plugin.

**Comment by Microno95** [comment]
I see how many solution could add significant complexity, but perhaps a purely python-side solution is the most sensible way to handle it.

If we were to assign unique IDs to each scene (i.e. when they're loaded) and have `SceneParameters` act as a front-end for a global registry of scene parameters. So the first time you call `mi.traverse(scene)` this creates an entry in this global register of scenes that stores a reference to the `SceneParameters` that is obtained through traversal - something like a dict that is a class property rather than an instance property.

On calling `mi.render` or `integrator.render`, the dispatch to the underlying function can then check this registry to see if a) a scene has been loaded into it, and b) if the referenced scene has any dirty parameters. If dirty parameters are found, then either `params.update()` is silently called (this is undesirable is my understanding) or an `Exception` is raised indicating that `render` was called on a scene with dirty parameters. I realise that this adds an additional layer on top of the python api and probably would incur some overhead, but it should be minimal since it would simply be a membership test (for the scene ID) and a dirty parameter check (as easy as a flag or a `len(dirty_params)>0` test).

The only key thing to ensure is that whenever traverse is called on the same scene object, the same `SceneParameters` must be returned, so there should only be one instance of `SceneParameters` per unique scene (a copy of a scene would count as a new scene).

At a high-level this should mostly alleviate the problem and make it harder to break the python side of things. Alternatively, the `SceneParameters` object could be moved to the C++ side where it should be easier to create and manage singletons without the wrinkles of Python.

**Comment by leroyvn** [comment]
FWIW: I recently extended `SceneParameters` and modified the `traverse()` logic for my project by providing alternative implementations — rather than modifying the Mitsuba codebase directly. We would lose some of this flexibility if `SceneParameters` would have class state `mi.render()` relies on. So I'm personally don't know if I would enjoy such a solution.

The least intrusive alternative I can think of is to encapsulate a `Scene` and the corresponding `SceneParameters` in a small object that would provide an alternative to `mi.render()` — which would simply perform a dirty check or call `self.params.update()` before rendering.

**Comment by Speierers** [comment]
> encapsulate a Scene and the corresponding SceneParameters in a small object that would provide an alternative to mi.render()

I have done something similar in my current project. I have an object that wraps the scene and the corresponding parameters. It then exposes a getter for the underlying scene that makes sure things are up-to-date. 

`mi.render(wrapper.scene(), ...)`

**Comment by njroussel** [comment]
:+1: 

Monkey-patching whatever evaluation function you use (someone might not be using `mi.render()`, or an entire scene but rather just a single object like a BSDF) to add an update is definitely the easiest workaround.
